name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build library artifacts
        run: ./gradlew :pollingengine:build :pollingengine:assembleReleaseXCFramework --stacktrace
      - name: Generate docs
        run: ./gradlew :pollingengine:dokkaHtml --stacktrace
      - name: Publish to Sonatype (if secrets present)
        if: ${{ secrets.OSSRH_USERNAME != '' && secrets.OSSRH_PASSWORD != '' && secrets.SIGNING_KEY != '' && secrets.SIGNING_PASSWORD != '' }}
        env:
          ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          signing.key: ${{ secrets.SIGNING_KEY }}
          signing.password: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew :pollingengine:publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
      - name: Zip XCFramework
        run: |
          cd pollingengine/build/XCFrameworks/release
          zip -r PollingEngine.xcframework.zip PollingEngine.xcframework
      - name: Zip Dokka HTML
        run: |
          cd pollingengine/build/dokka/html
          zip -r ../../dokka-html.zip .
      - name: Attach artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pollingengine/build/XCFrameworks/release/PollingEngine.xcframework.zip
            pollingengine/build/dokka/dokka-html.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish docs to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pollingengine/build/dokka/html
          publish_branch: gh-pages
          force_orphan: true
